export enum TicketStatus {
  BACKLOG = 'BACKLOG',
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  REVIEW = 'REVIEW',
  DONE = 'DONE',
}

export interface Epic {
  id: string;
  name: string;
  color: string; // Hex code or Tailwind class fragment
}

export interface Ticket {
  id: string;
  title: string;
  description: string;
  status: TicketStatus;
  priority: 'low' | 'medium' | 'high' | 'critical';
  storyPoints: number;
  epicId?: string;
  assignee?: string;
  startDate?: string; // YYYY-MM-DD
  endDate?: string;   // YYYY-MM-DD
  aiInsights?: string; // Content generated by "Mother"
}

export interface ColumnType {
  id: TicketStatus;
  title: string;
}

export interface Project {
  id: string;
  name: string;
  tickets: Ticket[];
  epics: Epic[];
  description?: string;
}

export interface DragItem {
  id: string;
  fromStatus: TicketStatus;
}
