export enum TicketStatus {
  BACKLOG = 'BACKLOG',
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  REVIEW = 'REVIEW',
  DONE = 'DONE',
}

export interface Epic {
  id: string;
  name: string;
  color: string; // Hex code or Tailwind class fragment
}

export interface Ticket {
  id: string;
  title: string;
  description: string; // Supports markdown
  status: TicketStatus;
  impact: 'low' | 'medium' | 'high' | 'critical'; // Renamed from priority
  effort: number; // Renamed from storyPoints
  epicId?: string;
  assignee?: string;
  startDate?: string; // YYYY-MM-DD
  endDate?: string; // YYYY-MM-DD
  aiInsights?: string; // Content generated by "Mother"
  prUrl?: string; // GitHub PR URL
  prdUrl?: string; // PRD reference URL
  flagged?: boolean; // Important/urgent flag (like Jira)
  requiresHuman?: boolean; // Needs human intervention/decision
}

export interface ColumnType {
  id: string;
  projectId: string;
  title: string;
  statusKey: string;
  position: number;
}

export interface Project {
  id: string;
  name: string;
  tickets: Ticket[];
  epics: Epic[];
  columns: ColumnType[];
  description?: string;
  goal?: string;
}

export interface DragItem {
  id: string;
  fromStatus: TicketStatus;
}
